DROP TABLE IF card_payment CASCADE;

CREATE TABLE card_payment (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  card_number VARCHAR(255) NOT NULL,
  card_expiry VARCHAR(255) NOT NULL,
  ccv VARCHAR(255) NOT NULL
);