DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  -- menu_id INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  prep_time SMALLINT,
  cost INTEGER NOT NULL,
);
