-- DROP TABLE IF EXISTS _menu CASCADE;

-- CREATE TABLE _menu(
--   id SERIAL PRIMARY KEY NOT NULL,
--   restaurant_id INTEGER REFERENCES restaurants(id) ON DELETE CASCADE,
--   name VARCHAR(255) NOT NULL
-- );